###
GET http://localhost:3000/api/diaries


###
GET http://localhost:3000/api/diaries/2


###
POST http://localhost:3000/api/diaries
Content-Type: application/json

{
  "date": "2024-08-08",
  "weather": "rainy",
  "visibility": "poor",
  "comment": "is a bad day"
}
