###
GET http://localhost:3000/api/diaries


###
GET http://localhost:3000/api/diaries/2


###
POST http://localhost:3000/api/diaries
Content-Type: application/json

{
  "date": "2021-04-04",
  "weather": "sunny",
  "visibility": "good",
  "comment": "is a good day"
}
